### ISSUE TITLE
type: object and additionalProperties: type: array causing is not assignable to 'string' index type 

### ISSUE THREAD

**Issue by joshunger** [openapi-ts/openapi-typescript#1055]
**Description**

I'm seeing in our existing code we have a type object where we've defined additional properties as an array. When we run `openapi-typescript` the TypeScript produced doesn't compile. Should this work? Thanks for the help!

```
TS2411: Property 'totals' of type '{ count?: number; }' is not assignable to 'string' index type 'Record<string, never>[]'.
    10 |     B: Record<string, never>;
    11 |     Example: {
  > 12 |       totals?: {
       |       ^^^^^^
    13 |         count?: number;
    14 |       };
    15 |       [key: string]: (components['schemas']['A'] & components['schemas']['B'])[] | undefined;
```

| Name                 | Version                      |
|:---------------------|:-----------------------------|
| `openapi-typescript` | `6.2.0`                      |
| Node.js              | `14.17.6`                      |
| OS + version         | `macOS 13` |

**Reproduction**

schema.yaml
```
components:
  schemas:
    A:
      type: object
    B:
      type: object
    Example:
      type: object
      properties:
        totals:
          type: object
          properties:
            count:
              type: integer
      additionalProperties:
        type: array
        items:
          allOf:
            - $ref: '#/components/schemas/A'
            - $ref: '#/components/schemas/B'
```

```
npx openapi-typescript ./schema.yaml
```

**Expected result**

Creates valid TypeScript that compiles.

**Checklist**

- [ ] I’m willing to open a PR (see [CONTRIBUTING.md](https://github.com/drwpow/openapi-typescript/blob/main/CONTRIBUTING.md))

**Comment by mitchell-merry** [comment]
This is a tricky one.

Let's take a simplified schema:
```yaml
Example:
  type: object
  properties:
    totals:
      type: number
  additionalProperties:
    type: string
```

v6 generates:
```ts
Example: {
  totals?: number;
  [key: string]: string | undefined;
};
```

while v5 generates:
```ts
Example: {
  totals?: number;
} & { [key: string]: string };
```

Note the difference - an intersection. While the v5 generated types _compile_, they're not actually useful, since trying to assign anything to that type will fail:
```ts
examples/1055_v5.ts:16:7 - error TS2322: Type '{ totals: number; }' is not assignable to type '{ totals: number; } & { [key: string]: string; }'.
  Type '{ totals: number; }' is not assignable to type '{ [key: string]: string; }'.
    Property 'totals' is incompatible with index signature.
      Type 'number' is not assignable to type 'string'.

const myExample: components["schemas"]["Example"] = {
  totals: 4
}
```

Following discussion from https://github.com/microsoft/TypeScript/issues/17867... there's a misunderstanding on what the index signature here actually means. If you were to index an object of this type with an arbitrary string, what would you expect? You would expect `string`, but if that string is `totals`, then you actually get number. See Ryan Cavanaugh's comment: https://github.com/microsoft/TypeScript/issues/17867#issuecomment-323176309

So, what we probably want to generate is actually:
```ts
Example: {
  totals?: number;
  [key: string]: string | undefined | number;
};
```

which works as on the tin. Index with an arbitrary string, and you get string, other than the case where the string happens to be `totals`, where it's number. So the type should be `string | number`.

Does that make sense? This is a genuine bug.

**Comment by joshunger** [comment]
@mitchell-merry excellent explanation!

**Comment by tyronen9** [comment]
I'm experiencing when trying to generate a wrapper for [Creditsafe's API](https://www.creditsafe.com/gb/en/enterprise/integrations/api-documentation.html).

The issue is at line 21764 of their spec:

```
"ProblemDetails": {
  "type": "object",
  "properties": {
      "title": "string"
      // etc
    }
  },
  "additionalProperties": {
    "type": "object"
  }
```

The generator produces

```
  ProblemDetails: {
    title?: string;
    // etc
    [key: string]: Record<string, never> | undefined;
  };
```

which is not valid TypeScript. But afaict this _is_ valid OpenAPI.

Basically it's all or nothing. If you have `additionalProperties` of type `object`, you can't have any _other_ properties.

The issue is that `key` could clash at runtime with any of the other fields. We'd need to define an enum consisting of all the keys of that type, then allow `key` to be any string _except_ that type. Not sure if this is possible.

**Comment by drwpow** [comment]
> The issue is that `key` could clash at runtime with any of the other fields. We'd need to define an enum consisting of all the keys of that type, then allow `key` to be any string _except_ that type. Not sure if this is possible.

I agree this is probably the right fix. And it should be possible.

**Comment by mitchell-merry** [comment]
I don't think it's currently possible to specify a type `string` except for a particular string. There is an issue open for negated types: https://github.com/microsoft/TypeScript/issues/4196 that would let us do something like `[key: string & not 'title']` for the index signature. Would be a good use case for that operand I suppose

**Comment by drwpow** [comment]
Yeah I’m wondering if reverting to the old behavior of an intersection + a TS helper (or it sounds crazy, but maybe a union, depending on how it behaves in practice) would yield better results until https://github.com/microsoft/TypeScript/issues/4196 resolves (which may not be anytime soon). I think it’s at least worth exploring some (non-breaking) TS shenanigans here.
