### ISSUE TITLE
SchemaObject type: 'string' should allow pattern?: string

### ISSUE THREAD

**Issue by Apollo314** [openapi-ts/openapi-typescript#1063]
https://github.com/drwpow/openapi-typescript/blob/206f28517f1707ec0d97ad72251323a0da6ad2f1/src/types.ts#L436

![image](https://user-images.githubusercontent.com/29009961/229336693-4eb8a448-ec78-40b0-9334-a502974ef498.png)

type: 'string' should allow `pattern?: string` as per the standard:

https://swagger.io/docs/specification/data-models/data-types/#string

otherwise it falsely assumes it is supposed to be type 'object' and gives an error that way.

![image](https://user-images.githubusercontent.com/29009961/229336870-164e364c-9ff4-4a35-b17e-b612e905e0a8.png)

it also should allow minLength and maxLength.

![image](https://user-images.githubusercontent.com/29009961/229337116-41b74b5f-a4b6-47e3-a70b-5625fd407f9e.png)

this fixes the errors.

**Comment by mitchell-merry** [comment]
Feel free to open a PR

**Comment by Apollo314** [comment]
turns out they were 3.0.x keywords. couldn't find it in 3.1.x specs.

**Comment by isobelhooper** [comment]
I've run into a similar problem - wanting to represent `pattern` for strings via openapi-typescript - and I think I found where the validation keywords are defined for OpenAPI 3.1.x, if that's sufficient encouragement to reopen this issue.

The validation keywords are no longer in the OpenAPI 3.1.x specification explicitly, but [the Schema Object section of the OpenAPI 3.1.x spec](https://spec.openapis.org/oas/v3.1.0#schema-object) starts with:

> The Schema Object allows the definition of input and output data types. These types can be objects, but also primitives and arrays. This object is a superset of the [JSON Schema Specification Draft 2020-12](https://tools.ietf.org/html/draft-bhutton-json-schema-00).
> 
> For more information about the properties, see [JSON Schema Core](https://tools.ietf.org/html/draft-bhutton-json-schema-00) and [JSON Schema Validation](https://tools.ietf.org/html/draft-bhutton-json-schema-validation-00).
>
> Unless stated otherwise, the property definitions follow those of JSON Schema and do not add any additional semantics.

and the [JSON Schema Validation](https://tools.ietf.org/html/draft-bhutton-json-schema-validation-00) link contains almost all of the validation keywords that were explicitly called out in [the Schema Object section of the 3.0.x OpenAPI spec](https://spec.openapis.org/oas/v3.0.0#properties). (`title` is not included, but the others all are, including `pattern` for strings.)

**Comment by drwpow** [comment]
@isobelhooper thanks for adding that! To be honest I didn’t really take a close look at this issue since the original author closed it. I’m not opposed to adding this, but what would the proposed generated types look like? Keeping in mind that this library intentionally does **NOT** validate at runtime, and though [string template literals](https://www.typescriptlang.org/docs/handbook/2/template-literal-types.html) are supported in TS, I’m not aware of a way to enforce RegEx.

If you or anyone could provide proposed types to generate (even as a trivial example) we could look into it, but just at first glance there didn’t seem to be a clear implementation path (to me).
