### ISSUE TITLE
Generate a separate interface for each omponents.schemas model

### ISSUE THREAD

**Issue by alex-aveva** [openapi-ts/openapi-typescript#1414]
**Description**

Generate a separate interface for each `components.schemas` model to provide a better development experience and easier models consumption.

**Proposal**

I've created a diff [PR](https://github.com/drwpow/openapi-typescript/pull/1413/files?diff=split&w=1) with the proposed changes, showing how the _final_ result would look. As you can see, it's a fairly straightforward change, but it can make a significant difference in how VSCode provides hints. You can compare the before and after screenshots below.

Before:
![image](https://github.com/drwpow/openapi-typescript/assets/138735161/709b8dcf-e7c7-4fc9-9797-b4a3515b8577)

After
![image](https://github.com/drwpow/openapi-typescript/assets/138735161/254682bc-301a-46ea-bf80-d70817998ffb)
![image](https://github.com/drwpow/openapi-typescript/assets/138735161/3aea157f-5cc1-4371-a294-3e94b8f8e065)

In real-world environments, having anonymous classes & hints is not very useful. Models often tend to be large, and in the many of cases, it's not even possible to determine which model you're looking at just by examining its shape. Providing a model interface name addresses this issue. It also enables referencing models by their interface names throughout the codebase, which is very convenient,

This perhaps can be an optional generator switch.

**Checklist**

- [x] I’m willing to open a PR for this (see [CONTRIBUTING.md](https://github.com/drwpow/openapi-typescript/blob/main/packages/openapi-typescript/CONTRIBUTING.md))

**Comment by drwpow** [comment]
Upon reading your proposal, this sounds like what’s in-progress here https://github.com/drwpow/openapi-typescript/pull/1260? 

I’m slightly-against this in general, because v1 of this library (long ago) took this approach and it quickly became untenable for many schemas. I wrote some thoughts here on some drawbacks of trying to generate separate interfaces for every schema object: https://github.com/drwpow/openapi-typescript/pull/1260#issuecomment-1658694431

And this is off-topic, but a related thought: [embrace snake_case](https://openapi-ts.pages.dev/advanced/#embrace-snake_case)

**Comment by drwpow** [comment]
This was released with the `--root-types` flag!

**Comment by saminahbab** [comment]
Huge thanks to whoever it was that helped with this
appreciate that it might break a lot of oapi schemas, but without root types was having to reexport myself. 
much cleaner now. I'm happy.
