### ISSUE TITLE
Confusion about discriminator test case

### ISSUE THREAD

**Issue by H01001000** [openapi-ts/openapi-typescript#1449]
**Description**
Not sure if I understand correctly, for me it seems the discriminator should only exist on the parent schema, and not the child, where the discriminator mapping map the value it has to the child type/$ref. If I am interpreting correctly, it seems the test cases for discriminator are having some issues, eg discriminator > oneOf, the child having discriminator, discriminator > allOf the child having discriminator and point to the parent

may related to #1158

| Name                 | Version                      |
| :------------------- | :--------------------------- |
| `openapi-typescript` | `7.0.0-next.0`                      |
| Node.js              | `18.12.0`                      |
| OS + version         | `Windows 10` |

**Checklist**

- [x] My OpenAPI schema passes the [Redocly validator](https://redocly.com/docs/cli/commands/lint/) (`npx @redocly/cli@latest lint`)
- [x] I’m willing to open a PR (see [CONTRIBUTING.md](https://github.com/drwpow/openapi-typescript/blob/main/packages/openapi-typescript/CONTRIBUTING.md))

**Comment by drwpow** [comment]
Just so I’m clear, could you point to the specific test you’re referring to, and what you think the correct output types should be?

In general, though, there’s not really a “parent–child” relationship when it comes to composition. When you mark something as `allOf` you are really just extending that object. I don’t think it’s accurate to call it a “child” node because same level; you’re just saving yourself some typing. So I think you’re intentionally not redeclaring a discriminator when using composition.

But I may be off the mark / missing something. Happy to talk through a more specific example of what’s generated today vs. what you expect to happen if you provide one
