### ISSUE TITLE
Export component's and path's types with friendly names

### ISSUE THREAD

**Issue by enkot** [openapi-ts/openapi-typescript#1598]
**Description**

First of all, I want to thank you for this great lib! :) 
To make it even better, I suggest exporting component types and paths like open-api-generator does.

**Proposal**

The first attempt to implement this is here https://github.com/drwpow/openapi-typescript/pull/1260.
The idea is to generate types like this:
Components:
```ts
export type SchemaSimpleUser = components["schemas"]["simple-user"];
export type SchemaInstallation = components["schemas"]["installation"];
...
export type ResponseNotFound = components["responses"]["not_found"];
export type ResponseRequiresAuthentication = components["responses"]["requires_authentication"];
...
export type ParameterPerPage = components["parameters"]["per-page"];
export type ParameterPage = components["parameters"]["page"];
...
export type HeaderLink = components["headers"]["link"];
export type HeaderXRateLimitLimit = components["headers"]["x-rate-limit-limit"];
```
Paths:
```ts
export type RequestEnterpriseAdminListGlobalWebhooks = paths["/admin/hooks"]["get"]["parameters"];
export type RequestEnterpriseAdminGetGlobalWebhook = paths["/admin/hooks/{hook_id}"]["get"]["parameters"];
```
It would be also nice to generate types for `requestBody` and `responses`, but not sure how to properly handle content type (`application/json`, `application/yaml` etc.)

We also need to resolve the duplication issue described in this comment https://github.com/drwpow/openapi-typescript/pull/1260#issuecomment-1658694431. This can be solved by adding a number as a suffix to the duplicate name.

**Checklist**

- [x] I’m willing to open a PR for this (see [CONTRIBUTING.md](https://github.com/drwpow/openapi-typescript/blob/main/packages/openapi-typescript/CONTRIBUTING.md))

**Comment by drwpow** [comment]
Just for cleanup: this already exists at #1414; closing this to track that.

This solution has been frequently-requested, but is fraught with problems and gotchas (since OpenAPI allows so many characters that are not valid JS identifiers, not to mention conflicts, it makes this approach non-deterministic and full of edge cases that amount to a significant amount of work, to result in what is only a cosmetic difference of what’s available in the library today.

The current status of this is if someone can open a PR that meets full requirements this will be accepted, but so far it’s been too much work to take on.
