### ISSUE TITLE
Upgrade to openapi-fetch 0.9.x: Only absolute URLs are supported

### ISSUE THREAD

**Issue by jenwirth** [openapi-ts/openapi-typescript#1699]
Hi,

I am trying to figure why we are getting the following error after updating `openapi-fetch` from *0.8.x* to *0.9.x*:

```
⨯ TypeError: Only absolute URLs are supported
    at new Promise (<anonymous>)
    at Object.getAll (./src/services/location-service.ts:49:22)
    at page (./src/app/locations/page.tsx:18:101)
    at stringify (<anonymous>)
```

This is the code involved (which did not change between this version update)

```ts
const {GET: ssGET} = createClient<paths>({
    baseUrl: AppConfig.ssr.eventServiceBase,
    fetch: fetch
})
```

I can confirm the baseUrl is set correctly.

and where the error occurs 

```ts
    async getAll() {
        return await ssGET("/locations")
    },
```

thanks for any help!

**Comment by drwpow** [comment]
Internally there was a change from `fetch(url, init)` to `fetch(new Request(options))` to support middleware. Since this library is still pre-1.0, and it was the first pass at middleware, it was an experiment, but it’s given people problems! So I think we’ll probably revert that internal change and go back to `fetch(url, init)` in `0.10.0` (which may have a few other minor breaking changes as it will rely on `openapi-typescript@7.x`).

In pre-1.0 versions, every minor change usually comes with breaking changes, just FYI. At least until 1.0 and beyond, which will follow normal semver.

**Comment by tamlyn** [comment]
Was there a solution for this? How do I supply a custom `fetch` implementation in post-0.9 versions?

**Comment by jenwirth** [comment]
We have many projects failing over this. What is the solution? 

I have:

```ts
import fetch from "cross-fetch";
import createClient from "openapi-fetch";
…
const {GET: ssGET} = createClient<paths>({
    baseUrl: AppConfig.ssr.serviceBase,
    fetch: fetch
})
…
…
  async getAll() {
        return await ssGET("/foobar")
    },
```
