### ISSUE TITLE
Alternate version of `createClient` that takes `operationId`

### ISSUE THREAD

**Issue by edonv** [openapi-ts/openapi-typescript#1816]
**Description**

Would it be possible to create a generic alternate function to `createClient<paths>()` that has functions that take operation names/IDs rather than needing to use `GET`/`POST`/etc and the path? You need to know which operation was which method and path to use it the current way, which is fine for most cases. But generally speaking, you kind of need to be looking at the OpenAPI desc to be able to be able to use it specifically.

Alternatively, maybe there could be a script or something tying into `openapi-typescript` that generates a type with named functions by the operation IDs.

**Proposal**

I'm by no means a pro at the more complex intricacies of TypeScript's generics and conditional types, but this is my attempt to adapt `ClientMethod`, `Client` and `createClient`, all using an extra generic type for the auto-generated `operations` interface from `openapi-interface`. It doesn't fully work with full type inference, but it shows errors when using incompatible parameters in the `call` function.

```ts
type ClientOperation<
  Operations extends Record<string, {}>,
  Paths extends Record<string, Record<HttpMethod, {}>>,
  Media extends MediaType,
> = <
  OperationID extends keyof Operations,
  Method extends HttpMethod,
  Path extends PathsWithOperation<Operations, OperationID, Paths, Method>,
  Init extends MaybeOptionalInit<Paths[Path], Method>
>(
  operationId: OperationID,
  url: Path,
  method: Method,
  ...init: HasRequiredKeys<Init> extends never
    ? [(Init & { [key: string]: unknown })?] // note: the arbitrary [key: string]: addition MUST happen here after all the inference happens (otherwise TS can’t infer if it’s required or not)
    : [Init & { [key: string]: unknown }]
) => Promise<FetchResponse<Operations[OperationID], Init, Media>>;

interface OpClient<Operations extends {}, Paths extends {}, Media extends MediaType = MediaType> {
  call: ClientOperation<Operations, Paths, Media>;
}

function createOpClient<Operations extends {}, Paths extends {}, Media extends MediaType = MediaType>(
  clientOptions?: ClientOptions,
): OpClient<Operations, Paths, Media>
```

**Checklist**

I can't commit to contributing myself, as I'm not skilled enough to make it fully work. Let me know if I can help anymore though!

**Comment by drwpow** [comment]
This is an interesting idea, and I love the creativity. Rethinking APIs is always a great idea, because most everything can be improved.

The challenge with using operationIDs is there has to be a runtime mapping from operation ID → path + method + request options. That means codegen would be required.

Others have asked for openapi-fetch to take the path of codegen, but that’s not the original design goal of this library; the original design goal was to create a typed fetch wrapper that doesn’t scale with your API. Whether you have a small or behemoth schema, your fetch client is the same size and never slows down at runtime. This is possible because you’re still typing out a basic `fetch` request, just in a slightly-different API. There some drawbacks to not using codegen, sure, such as it not remembering default headers you specified in `createClient`. So this library isn’t taking the stance of “all codegen is bad;” rather, there are plenty of existing codegen alternatives, and this is an instant, codegen-free approach (which was inspired by `openapi-typescript-fetch`).

Issues like this are very welcome, and improve the quality of the code by suggesting sometimes better alternatives! And I’m not opposed by this direction in general. But as-written, this would require codegen and that’s not something the current maintainers can take on as an additional project at the moment. But anyone curious to build it themselves should!

**Comment by edonv** [comment]
I appreciate the insight! Like I said, I'm not as skilled with complex generic and conditional types in TypeScript, but it seems possible to do generically without codegen, as I feel like I got close with it. That being said, I trust you know what you're talking about.

Regarding codegen, I think that might be my solution then, because my end goal is a `Client` wrapper class around `createClient` that encapsulates authentication and baseURL (which, side note, would be great if we could get that from `openapi-typescript`'s codegen from the desc's `servers` field), and has named functions from each operation ID. On a small scale, that's not too difficult to write manually, but for a large OpenAPI desc, it's tough to write one manually AND to be able to easily use `createClient` without more in-depth familiarity with the particular API.

If I were to write my own codegen script, what would be the easiest way to integrate with `openapi-typescript`'s generated code? Should I write something on top of it that uses its `transform`/`postTransform`? Thanks for any advice!

**Comment by drwpow** [comment]
> I feel like I got close with it.

Yeah I haven’t debugged what you wrote closely, but at a glance I agree that’s pretty close type-wise! But just dealing with pure JS, you’ll still need at minimum some object of all the operation IDs that get loaded in-memory; otherwise it won’t know what to pass in to the `fetch()` call.

> I'm not as skilled with complex generic and conditional types in TypeScript

You’ve already honed in on the central trick of this library with your `extends … ? A : B` ternary. This library mostly just strings these together many times over. A lot of the types are trial-and-error, and just take it one layer at a time. Start simply, and chain these together, and you pretty much can infer anything when everything comes together.

> If I were to write my own codegen script, what would be the easiest way to integrate with `openapi-typescript`'s generated code? Should I write something on top of it that uses its `transform`/`postTransform`? Thanks for any advice!

Yeah that’s one way to collect all the operation IDs in one pass, especially if you’re already using openapi-typescript. If you wanted to traverse it separately, I’d recommend using [Redocly’s bundle command](https://github.com/openapi-ts/openapi-typescript/blob/main/packages/openapi-typescript/src/lib/redoc.ts#L148) which can drastically simplify the complexity of any schema (especially multi-file). But you may still have to deal with resolving aliases which isn’t terrible; just a little bit of manual work.

Also when codegen-ing, it’s up to you whether to use the TypeScript AST (like this library does) or simple string mashing. I personally prefer prototyping with string mashing because it’s much faster to experiment initially. You can always switch to the AST later once you like what you have.

Lastly, [file snapshot tests](https://vitest.dev/guide/snapshot#file-snapshots) are key with any codegen. Though I’m not a strict adherent to TDD, I think codegen specifically is where TDD really shines and saves so much work in debugging. Plus, if you write tests by hand, I find working backwards from what you want the final code to look like, is much easier to deal with, especially when the internals can get hairy.

All of the following just take as random hints to take or leave; it may or may not work for you! Just anecdotally listing out some learnings from building these libraries myself 🙂

**Comment by edonv** [comment]
Thanks for the advice, I really appreciate it! I come from the Swift world, so my experience with codegen is (a) string mashing (I did it for a project a while back), and (b) AST with Swift Macros which is built on `swift-syntax` (Apple's AST library).

We'll see what I can come up with!

**Comment by mylesmmurphy** [comment]
Desired end result, modeled after the example shown [here](https://github.com/openapi-ts/openapi-typescript/blob/main/packages/openapi-fetch/examples/nextjs/app/page.tsx#L4C1-L10C2)

**Current Implementation:**
`
async function getFact() {
  return await client.GET("/fact", {
    params: {
      query: { max_length: 500 },
    },
  });
}
`

**Proposed Implementation:**
`
async function getFact() {
  return await client.getFact({
    params: {
      query: { max_length: 500 },
    },
  });
}
`
**Assumption**: The OpenAPI specification defines the operationId for the `/fact` endpoint as `getFact`.

**Comment by drwpow** [comment]
@mylesmmurphy Oh yeah you‘re always welcome to add thoughts to a closed issue! And appreciate the suggestion (now is a great time for feedback as we plan openapi-fetch@1.0). Unfortunately that specific suggestion _as-posed_ (emphasis on _as-posed_; will return to the overall suggestion) is something we’d intentionally like to avoid for the following reasons:

1. > it could take an in-memory object of a parsed OpenAPI Spec

    This library intentionally does not have such a thing—some specs would be megabytes in size. We have no runtime awareness of the OpenAPI spec, to keep this as lightweight as possible

2. > dynamically create methods based on the operation IDs in that spec with full type safety. … I believe this would be a relatively simple and extremely lightweight solution that avoids codegen altogether.

    One of this library’s core goals is squeezing every last drop of performance out of it so it’s as close as native `fetch()` as possible. There’s always a tradeoff, too—codegen does require an annoying build step but it can optimize runtime. Conversely, doing more in runtime can save codegen, but moving the work into the client, onto user’s machines isn’t necessarily the right call either because now the compute is multiplied. Of the two, I think we‘d probably prefer having _some_ intelligent codegen over a slower runtime (I realize that some of the language in docs and issues may seem “anti-codegen,” but a more accurate take is this library is more fundamentally “anti-_WASTEFUL_ codegen” where you just have bloat on the client).

So if we could back up, and perhaps consider some sort of a _light_ codegen approach where we simply make operationID aliases, I think that’s an idea we’d consider for the roadmap 🙂. There are a number of other issues that, if we’re collecting input, have received more support in favor of users wanting some light codegen to solve some trickier issues (i.e. a response we get is that consumers would take on a few more KB and an itty bitt performance hit in order to have a couple pain points like this smoothed over, and we’re listening)

**Comment by mylesmmurphy** [comment]
Hey @drwpow Thanks for the quick reply and context—I definitely appreciate the focus on keeping things lean and performant. 😄 

I wanted to follow up on Option 1, since I still believe it’s a viable pattern worth considering. There’s precedent for passing a parsed OpenAPI spec at runtime in widely-used libraries like [swagger-ui-express](https://www.npmjs.com/package/swagger-ui-express), which accepts the parsed spec object directly. In my own testing, parsing and referencing the OpenAPI JSON was extremely fast—even with very large specs like the [Microsoft Graph API](https://github.com/microsoftgraph/msgraph-metadata/blob/master/openapi/v1.0/openapi.yaml), execution averaged around 8ms locally. For more typical API specs, the time was consistently **under 0.05ms**. While performance can vary by environment, this suggests the runtime cost is negligible in most real-world scenarios unless misused.

<details>
<summary>Local Performance Test</summary>

```typescript
console.time("json-test");

import spec from "./openapi.json";

const test: Record<string, () => string> = {};

for (const path in spec.paths) {
  const pathItem = spec.paths[path];

  // Iterate over HTTP methods (e.g., get, post, etc.) in the path item
  for (const method in pathItem) {
    const operation = pathItem[method as keyof typeof pathItem];

    // Ensure the operation has an operationId
    if (operation && operation.operationId) {
      const operationId = operation.operationId;

      // Add an anonymous function to the test record
      test[operationId] = () => path;
    }
  }
}

console.timeEnd("json-test");

console.log(Object.keys(test).length, "operations found");
```
</details>

I totally understand and respect the goal of keeping `openapi-fetch` lightweight and close to native `fetch()`. That said, I wonder if there’s room for an optional, opt-in layer—perhaps a separate utility or wrapper—that accepts a parsed spec and maps operationIds at runtime. This would let the core package remain minimal and fast, while giving users who prefer a dynamic client the flexibility to do so without requiring a codegen step. It could be left up to the consumer to make performance tradeoffs.

All that said, I’m definitely open to a light codegen path as well—especially if it’s just creating operationId aliases. I'm open to either path 😄 

Thanks again for the open discussion and for the great work on this project!

**Comment by drwpow** [comment]
> I wanted to follow up on Option 1, since I still believe it’s a viable pattern worth considering. There’s precedent for passing a parsed OpenAPI spec at runtime in widely-used libraries like [swagger-ui-express](https://www.npmjs.com/package/swagger-ui-express), which accepts the parsed spec object directly. In my own testing, parsing and referencing the OpenAPI JSON was extremely fast—even with very large specs like the [Microsoft Graph API](https://github.com/microsoftgraph/msgraph-metadata/blob/master/openapi/v1.0/openapi.yaml), execution averaged around 8ms locally.

That’s great prior art! OK I can see where you’re coming from and I’d be happy to surface the idea to the other maintainers (in particular, they’ll be driving openapi-fetch 1.0 more than I will be!). Thanks for providing more context. It’s probably more accurate to say “I wouldn’t feel comfortable _pioneering_ the idea of keeping an OpenAPI schema in runtime in every client,” however, I think in general we’d be very open to the idea of “by default you don’t have to have an OpenAPI schema loaded in memory, however, if you [follow existing pattern XYZ and are already using it], here’s an opt-in path to take advantage of that.”

**Comment by mylesmmurphy** [comment]
Sure thing! I can definitely share more examples if helpful, but off the top of my head, I’ve also used [express-openapi-validator](https://www.npmjs.com/package/express-openapi-validator), which follows this same pattern. 😄

If the other maintainers are interested in exploring this direction, I’d be happy to take a first stab at a PR against the current version. I totally understand if timing or scope isn’t right—I don’t want to step on any toes. 😅

**Comment by mylesmmurphy** [comment]
Hi @drwpow, wanted to follow up here 😄 If interested, I would be happy to open a PR to add this. My team did determine we needed to continue using operation based methods, but I was able to use the types exported here to implement myself using the approach mentioned above fairly easily. Would be ideal still if it could be integrated directly into this package 🥳 

After reviewing the codebase, I believe the following contract could fit in nicely:

```typescript
const client = createClient<paths>(clientOptions);
const operationBasedClient = wrapAsOperationBasedClient<operations>(client, openApiSpec);

operationBasedClient.myUrlOperationId(fetchOptions);

// OR...

const client = createOperationBasedClient<paths, operations>(clientOptions, openApiSpec); // Could also make openApiSpec a required prop of clientOptions here instead
```

Thanks either way!

**Comment by jakiestfu** [comment]
@mylesmmurphy Mind sharing any code you have for your implementation?

**Comment by mylesmmurphy** [comment]
Hey @jakiestfu! Absolutely, below is an example of how to achieve this. I've tried to have the code copy the patterns set by openapi-ts as closely as possible, but this could also be achieved without using a proxy. This implementation is more of a draft instead of a finished product, so there may be bugs.

Using the [Petstore](https://petstore3.swagger.io/#/pet/findPetsByStatus) example ([JSON](https://petstore3.swagger.io/api/v3/openapi.json)). OpenAPI TS has been ran as well to create `./schema`.

```typescript
import type { FetchOptions, FetchResponse, Client, ClientOptions } from 'openapi-fetch';
import type { HttpMethod, MediaType, RequiredKeysOf } from 'openapi-typescript-helpers';
import createClient from "openapi-fetch";

import type { paths, operations } from "./schema";
import spec from "./petstore.json"

/********************* Types *********************/

type OperationMaybeOptionalInit<Operation extends Record<string, any> = Record<string, any>,> = RequiredKeysOf<FetchOptions<Operation>> extends never
  ? FetchOptions<Operation> | undefined
  : FetchOptions<Operation>;

type InitParam<Init> = RequiredKeysOf<Init> extends never
  ? [(Init & { [key: string]: unknown })?]
  : [Init & { [key: string]: unknown }];

type OperationClientMethod<
  Operation extends Record<string, any>,
  Media extends MediaType,
> = <Init extends OperationMaybeOptionalInit<Operation>>(
  ...init: InitParam<Init>
) => Promise<FetchResponse<Operation, Init, Media>>;

type OperationBasedClient<Operations extends Record<string, any>, Media extends MediaType = MediaType> = {
  [Operation in keyof Operations]: OperationClientMethod<Operations[Operation], Media>;
};

/********************* Client Functions *********************/

class OperationClientProxyHandler {
  client: Record<string, any> | null;
  private readonly operations: Record<string, { path: string; method: HttpMethod }> = {};

  constructor(openApiSpec: Record<string, any>) {
    this.client = null;

    const paths = openApiSpec.paths;

    for (const pathName in paths) {
      const path = paths[pathName];
      if (typeof path !== 'object' || !path) continue;

      for (const methodName in path) {
        const method = path[methodName];
        if (typeof method !== 'object' || !method?.operationId) continue;

        this.operations[method.operationId] = {
          path: pathName,
          method: methodName as HttpMethod
        };
      }
    }
  }

  get(coreClient: Client<any, any>, operationId: string) {
    if (this.client === null) return undefined;

    this.client[operationId] = undefined;

    const operation = this.operations[String(operationId)];
    if (operation) {
      const requestHandler = (...args: any[]) => (coreClient as any).request(operation.method, operation.path, ...args);
      this.client[operationId] = requestHandler;
    }

    return this.client[operationId];
  }
}

/**
 * @see https://github.com/openapi-ts/openapi-typescript/blob/main/packages/openapi-fetch/src/index.js#L362
 */
function wrapAsOperationBasedClient<Operations extends Record<string, any>, Media extends MediaType = MediaType>(
  coreClient: Client<{}, Media>,
  openApiSpec: Record<string, any>,
): OperationBasedClient<Operations, Media> {
  const handler = new OperationClientProxyHandler(openApiSpec);
  const proxy = new Proxy(coreClient, handler);

  function Client() {}
  Client.prototype = proxy;

  // @ts-expect-error TS7009: plain function lacks a construct signature; intentional
  const client = new Client();

  handler.client = client;

  return client;
}

function createOperationBasedClient<Operations extends Record<string, any>, Media extends MediaType = MediaType>(
  openApiSpec: Record<string, any>,
  clientOptions?: ClientOptions,
): OperationBasedClient<Operations, Media> {
  return wrapAsOperationBasedClient(createClient(clientOptions), openApiSpec);
}

/********************* Test *********************/

const clientOptions: ClientOptions = { baseUrl: "https://petstore3.swagger.io/api/v3/" }

// Operation-based client creation
const operationClient = createOperationBasedClient<operations>(spec, clientOptions);

// Operation-based client with wrapped operations
const client = createClient<paths>(clientOptions);
const wrappedOperationClient = wrapAsOperationBasedClient<operations>(client, spec);

async function main() {
  const response = await client.GET('/pet/findByStatus', {
    params: {
      query: {
        status: 'available'
      }
    }
  })

  const operationResponse = await operationClient.findPetsByStatus({
    params: {
      query: {
        status: 'available'
      }
    }
  });

  const wrappedResponse = await wrappedOperationClient.findPetsByStatus({
    params: {
      query: {
        status: 'available'
      }
    }
  });

  console.dir(response.data?.[0]);
  console.dir(operationResponse.data?.[0]);
  console.dir(wrappedResponse.data?.[0]);
}

main().catch(console.error);

```

@drwpow Any updates on the possibility of adding this to the library? Otherwise if it's not within the scope of this project, I'd be happy to publish the wrapper I sent above 😄 

Edit: Just noticed original source code memoizes proxy calls, I'll post here later with updated code to match that pattern

Edit 2: Updated to use proxy pattern with memoized calls, based on [wrapAsPathBasedClient](https://github.com/openapi-ts/openapi-typescript/blob/main/packages/openapi-fetch/src/index.js#L362)

**Comment by mylesmmurphy** [comment]
@drwpow quick bump ^ 🙏

**Comment by djMax** [comment]
(IMHO a separate package does seem a reasonable thing for this use case since it has different runtime footprint characteristics)

**Comment by mylesmmurphy** [comment]
Hey @djMax! I think that makes sense, that would further enable it as an opt-in layer.

@drwpow is that something you’d consider adding as a package to this project directly? If so, I’d love to open a PR.
