### ISSUE TITLE
astToString is no longer exported

### ISSUE THREAD

**Issue by martinffx** [openapi-ts/openapi-typescript#1884]
**Description**

I'm trying to generate a client from an API definition and am following the guide here: https://openapi-ts.dev/node#usage

```
import fs from "node:fs";
import openapiTS, { astToString } from "openapi-typescript";

const ast = await openapiTS(new URL("./my-schema.yaml", import.meta.url));
const contents = astToString(ast);

// (optional) write to file
fs.writeFileSync("./my-schema.ts", contents);
```

but `astToString` is not publicly exported and I get:

```
npx tsx ./scripts/GenOpenAPI.ts
TypeError: (0 , import_openapi_typescript.astToString) is not a function
    at generateClient (/Users/martin/code/clearing/fee-service/scripts/GenOpenAPI.ts:7:22)
```

**Reproduction**

```
import fs from "node:fs/promises";

import { ApiSpec } from "../src/types/schema";

async function generateClient(): Promise<void> {
    const ast = await openapiTS(ApiSpec);
    const contents = astToString(ast);

    await fs.writeFile("../build/src/clients/client.d.ts", contents);
}

generateClient().catch((error) => console.error(error));
```

**Expected result**

I expect the documentation to work i.e. the function is exported or the documentation is updated.

**Checklist**

- [x] My OpenAPI schema passes the [Redocly validator](https://redocly.com/docs/cli/commands/lint/) (`npx @redocly/cli@latest lint`)
- [x] I’m willing to open a PR (see [CONTRIBUTING.md](https://github.com/openapi-ts/openapi-typescript/blob/main/packages/openapi-typescript/CONTRIBUTING.md))

**Comment by drwpow** [comment]
This is still exported and works in Node.js. This is an issue with `tsx` which may be transpiling to CommonJS or transforming the module in an unexpected way based on your TSConfig settings. You may have to fish it out of the `.default` export somehow.

**Comment by drwpow** [comment]
I’d recommend transpiling to ESM rather than CommonJS (not sure what `tsx` does out-of-the-box). Or using something like `vite-node` which has much better ESM support.

Going to close because we have tests that run on this, but please re-open if you are encountering the same with pure Node.js (no `tsx`)

**Comment by martinffx** [comment]
Should the import in the docs not be updated?

```
import openapiTS, { astToString } from "openapi-typescript";
```

**Comment by drwpow** [comment]
No that import is correct if using ESM! That syntax you’re using (`import`/`export`) is ESM. 
But you’re not running your Node.js code in ESM mode, and are using transpilers (tsx). This is the cost of using them—the import statements get transformed and may not match up. I’d recommend updating your code to use ESM if possible. This library isn’t designed to use CommonJS (`require`/`module.exports`) as a first-class experience (not since Node supports ESM natively now).
