### ISSUE TITLE
How to change response ts type when use middleware

### ISSUE THREAD

**Issue by QJvic** [openapi-ts/openapi-typescript#2007]
**Description**

How to change response ts type when using middleware. 
For example, I want return `response.data.data` using middleware, but  the result ts type of `client.GET`  is still original response.

**Checklist**

- [x] I’m willing to open a PR for this (see [CONTRIBUTING.md](https://github.com/openapi-ts/openapi-typescript/blob/main/packages/openapi-fetch/CONTRIBUTING.md))

**Comment by drwpow** [comment]
This unfortunately isn’t possible. This library works by using types generated from your schema, so that’s the contract it’s holding to. In order to change the types for `response.data.data`, you need to update your OpenAPI schema. Otherwise you run into the situation where your OpenAPI schema doesn’t accurately describe your endpoints, which can lead to bugs!

There may be a usecase where you may want to override your OpenAPI schema for some requests here and there, but if you started using generics per-request, you are basically overriding your OpenAPI types anyway. I think practically it would amount to the same end result as just overriding types.

I’m going to close this issue as “won’t implement,” however, if you came up with a full proposal for how this could work, or a proof of concept showing this is possible, I’d take a second look!
