### ISSUE TITLE
default-non-nullable does not seem to work for query parameters.

### ISSUE THREAD

**Issue by glumb** [openapi-ts/openapi-typescript#807]
<img width="1059" alt="image" src="https://user-images.githubusercontent.com/3062564/142685473-dfe054d6-c3f6-4f61-a3e5-ef14bb0e67a2.png">

I'm using the cli tool like this
```terminal
npx openapi-typescript --default-non-nullable openapi.yml --prettier-config .prettierrc --output typeApi.ts
```
But still the query parameters with a default value are optional type properties.

**Comment by drwpow** [comment]
Yes I believe `--default-non-nullable` should probably enforce the behavior you’re describing, unless it conflicts with another test. Would love for someone to open a PR if they’re able to!

**Comment by MarcErdmann** [comment]
Are there any updates on this issue?

**Comment by npbenjohnson** [comment]
I'm not sure this change makes sense in line with what REST and swagger are actually communicating. From swagger: "The default value is the one that the server uses if the client does not supply the parameter value in the request". If this change is implemented, the default value would never be used because typescript would require the client to always define it.

**Comment by MarcErdmann** [comment]
@npbenjohnson We use the types at the server actually.
